1.Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [48]:
def AlexandreTheophileVandermode(inp,increasing = False):
    N = len(inp)
    output = np.empty((N,N),dtype=object)
    if(increasing == False):
        for i in range(N):
            for j in range(N):
                pv = N-j-1
                output[i][j]= inp[i]**pv
    else:
        for i in range(N):
            for j in range(N):
                pv = j
                output[i][j]= inp[i]**pv
    return output

In [49]:
AlexandreTheophileVandermode([1,2,3,5],increasing = True)

array([[1, 1, 1, 1],
       [1, 2, 4, 8],
       [1, 3, 9, 27],
       [1, 5, 25, 125]], dtype=object)

In [50]:
AlexandreTheophileVandermode([1,2,3,5],increasing = False)

array([[1, 1, 1, 1],
       [8, 4, 2, 1],
       [27, 9, 3, 1],
       [125, 25, 5, 1]], dtype=object)

In [51]:
AlexandreTheophileVandermode([1,2,3,5])

array([[1, 1, 1, 1],
       [8, 4, 2, 1],
       [27, 9, 3, 1],
       [125, 25, 5, 1]], dtype=object)

Problem Statement 2:
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below
i 1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == ==
Input 10 20 30 40 50 60 70 80 90 100
y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4
Thus, the moving average sequence has n-k+1=10-4+1=7 values.

In [52]:
def MovingAverageSequence(input,windowsize):
    if(windowsize>0):
        input_len = len(input)
        output_len = input_len-windowsize+1
        output = np.empty(output_len,dtype=object)
        for i in range(output_len):
            output[i] = int(np.sum(input[i:i+windowsize])/windowsize)
        return output
    else:
        print("Window size should be greater than 0")

In [53]:
input =[10,20,30,40,50,60,70,80,90,100]
MovingAverageSequence(input,4)

array([25, 35, 45, 55, 65, 75, 85], dtype=object)

In [54]:
input=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
MovingAverageSequence(input,5)

array([3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13], dtype=object)

In [55]:
input = [3,5,7,2,8,10,11,65,72,81,99,100,150]
MovingAverageSequence(input,3)

array([5, 4, 5, 6, 9, 28, 49, 72, 84, 93, 116], dtype=object)